services:
    - type: web
      name: notices-monitor-backend
      runtime: node
      plan: free
      buildCommand: npm install
      startCommand: npm start
      envVars:
          - key: NODE_ENV
            value: production
          - key: PORT
            value: 3000
